name: Auto-assign issue on /attempt comment

on:
  issue_comment:
    types: [created]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = context.payload.comment;
            const issue = context.issue;

            if (comment.body.startsWith('/attempt')) {
              if (!issue.assignee) {
                github.rest.issues.assignees.add({
                  issue_number: issue.number,
                  assignees: [comment.user.login]
                });
                await github.rest.issues.createComment({
                  issue_number: issue.number,
                  body: 'Assigned the issue to you!'
                });
              } else {
                await github.rest.issues.createComment({
                  issue_number: issue.number,
                  body: 'This issue is already assigned. Tag a maintainer if you need to take over.'
                });
              }
            }
